global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "grpc-server"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9090"
